name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "ModbusF103"
          - "ModbusF429"
          - "ModbusH743"

    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: build
        uses: Qful/cubeide-action@master
        with:
          project-path: Examples/${{ matrix.example }}
          project-target: ${{ matrix.example }}

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.example }}
          path: Examples/${{ matrix.example }}/Debug/${{ matrix.example }}.bin
